window.PORTFOLIO_GAMES = [
  {
    id: "sakura",
    title: "小樱魔法卡",
    tags: ["卡牌", "休闲", "治愈"],
    coverImage: "assets/covers/sakura-cover.png",
    coverStyle: "#1a0d18",
    coverPosition: "center top",
    entry: "games/sakura/index.html",
    desc: "手势即魔杖，隔空召唤魔法阵",
    btnText: "立即召唤",
    introBadge: "H5 · 手势互动",
    introTips: [
      "需授权摄像头用于手势识别，画面在本地处理",
      "建议使用 Chrome / Edge 等现代浏览器",
      "左侧加载真实游戏后，可随时用「全屏体验」或顶部「全屏」沉浸游玩",
    ],
  },
  {
    id: "tarot",
    title: "心灵塔罗牌",
    tags: ["塔罗", "心灵", "每日"],
    coverImage: "assets/covers/tarot-cover.jpg",
    coverStyle: "#c9a01e",
    coverPosition: "center top",
    entry: "games/tarot/index.html",
    desc: "隔空抽取你的命运之牌，解读今日启示",
    btnText: "立即抽牌",
    introBadge: "H5 · 塔罗 · 手势",
    introTips: [
      "需授权摄像头用于隔空抽牌，数据不上传服务器",
      "建议在光线充足、正对摄像头的环境下游玩",
      "点「全屏体验」会先请求摄像头权限，授权后自动进入全屏",
    ],
  },
  {
    id: "coming-soon",
    title: "开发中…",
    tags: [],
    coverStyle: "none",
    entry: "",
    desc: "更多精彩小游戏敬请期待",
    btnText: "",
    comingSoon: true,
  },
];
