window.PORTFOLIO_GAMES = [
  {
    id: "sakura",
    title: "小樱魔法卡",
    tags: [],
    coverImage: "assets/covers/sakura-cover.png",
    coverStyle: "#1a0d18",
    coverPosition: "center top",
    entry: "games/sakura/index.html",
    desc: "手势即魔杖，隔空召唤魔法阵",
    btnText: "立即召唤",
    introBadge: "H5 · 手势互动",
    introTips: [
      "需授权摄像头用于手势识别，画面全程本地处理。放心，没有账号登录，也不收集任何数据！",
      "手机、电脑、平板浏览器都能玩，安卓手机会卡顿，建议使用电脑或平板体验更爽！",
      "服务器不太稳定，打不开请多刷新几次或换个浏览器体验。",
      "点「全屏体验」进入沉浸模式，效果拉满！",
    ],
  },
  {
    id: "tarot",
    title: "心灵塔罗牌",
    tags: [],
    coverImage: "assets/covers/tarot-cover.jpg",
    coverStyle: "#c9a01e",
    coverPosition: "center top",
    entry: "games/tarot/index.html",
    desc: "隔空抽取你的命运之牌，解读今日启示",
    btnText: "立即抽牌",
    introBadge: "H5 · 塔罗 · 手势",
    introTips: [
      "需授权摄像头用于手势识别，画面全程本地处理。放心，没有账号登录，也不收集任何数据！",
      "手机、电脑、平板浏览器都能玩，安卓手机会卡顿，建议使用电脑或平板体验更爽！",
      "服务器不太稳定，打不开请多刷新几次或换个浏览器体验。",
      "点「全屏体验」进入沉浸模式，效果拉满！",
    ],
  },
  {
    id: "coming-soon",
    title: "开发中…",
    tags: [],
    coverStyle: "none",
    entry: "",
    desc: "更多精彩小游戏敬请期待",
    btnText: "",
    comingSoon: true,
  },
];
