window.PORTFOLIO_GAMES = [
  {
    id: "linggen",
    title: "一掌鉴灵根",
    tags: [],
    coverImage: "assets/covers/linggen-cover.jpg",
    coverStyle: "#0a0f1a",
    coverPosition: "center center",
    entry: "games/linggen/index.html",
    desc: "伸出手掌，AR鉴定你的修仙灵根天赋",
    btnText: "开始鉴定",
    introBadge: "H5 · AR · 手势互动",
    cardBadge: { text: "新上线", type: "new" },
    qrOnly: true,
    qrUrl: "https://linggen.cyougames.site",
    qrImage: "assets/covers/linggen-qr.png",
    introTips: [
      "需授权摄像头用于手势识别，画面全程本地处理。放心，没有账号登录，也不收集任何数据！",
      "打开微信或相机扫描二维码，即可体验游戏。",
      "⚠️ 请注意：建议扫码后选择「在浏览器中打开」（如 Safari、Chrome等），不建议直接使用微信内置浏览器，以免部分互动功能受限，导致游戏体验不完整。"
    ],
  },
  {
    id: "tarot",
    title: "心灵塔罗牌",
    tags: [],
    coverImage: "assets/covers/tarot-cover.jpg",
    coverStyle: "#c9a01e",
    coverPosition: "center top",
    entry: "games/tarot/index.html",
    desc: "隔空抽取你的命运之牌，解读今日启示",
    btnText: "立即抽牌",
    introBadge: "H5 · 塔罗 · 手势",
    cardBadge: { text: "热门", type: "hot" },
    introTips: [
      "需授权摄像头用于手势识别，画面全程本地处理。放心，没有账号登录，也不收集任何数据！",
      "手机、电脑、平板浏览器都能玩，安卓手机会卡顿，建议使用电脑或平板体验更爽！",
      "服务器不太稳定，打不开请多刷新几次或换个浏览器体验。",
      "点「全屏体验」进入沉浸模式，效果拉满！",
    ],
  },
  {
    id: "sakura",
    title: "小樱魔法卡",
    tags: [],
    coverImage: "assets/covers/sakura-cover.png",
    coverStyle: "#1a0d18",
    coverPosition: "center top",
    entry: "games/sakura/index.html",
    desc: "手势即魔杖，隔空召唤魔法阵",
    btnText: "立即召唤",
    introBadge: "H5 · 手势互动",
    introTips: [
      "需授权摄像头用于手势识别，画面全程本地处理。放心，没有账号登录，也不收集任何数据！",
      "手机、电脑、平板浏览器都能玩，安卓手机会卡顿，建议使用电脑或平板体验更爽！",
      "服务器不太稳定，打不开请多刷新几次或换个浏览器体验。",
      "点「全屏体验」进入沉浸模式，效果拉满！",
    ],
  }
];
